name: auto-label
on:
  issues:
    types: [opened]
jobs:
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - run: gh issue edit $ISSUE --add-label team/devprod
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}
